name: Build FFmpeg with LAME support

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  LAME_VERSION: "3.100"
  ANDROID_API_LEVEL: 25
  NDK_VERSION: r27c

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86_64, x86]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # NDK setup
    - name: Set up Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: ${{ env.NDK_VERSION }}
        add-to-path: true
        
    - name: Verify NDK
      run: |
        echo "NDK Path: $ANDROID_NDK_HOME"
        ls -la $ANDROID_NDK_HOME/toolchains

    # Dependencies
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          nasm \
          git \
          wget

    # Download LAME
    - name: Download and extract LAME
      run: |
        wget https://downloads.sourceforge.net/project/lame/lame/${{ env.LAME_VERSION }}/lame-${{ env.LAME_VERSION }}.tar.gz -O lame.tar.gz
        tar -xzf lame.tar.gz
        mv lame-$LAME_VERSION lame
        rm lame.tar.gz

        echo "LAME_SOURCE_DIR=$GITHUB_WORKSPACE/lame" >> $GITHUB_ENV
        echo "LAME_BUILD_DIR=$GITHUB_WORKSPACE/lame-build" >> $GITHUB_ENV
        mkdir -p lame-build

    # Clone FFmpeg
    - name: Clone FFmpeg
      run: |
        git clone --depth 1 https://github.com/FFmpeg/FFmpeg.git ffmpeg

        echo "FFMPEG_SOURCE_DIR=$GITHUB_WORKSPACE/ffmpeg" >> $GITHUB_ENV
        echo "FFMPEG_BUILD_DIR=$GITHUB_WORKSPACE/ffmpeg-build" >> $GITHUB_ENV
        mkdir -p ffmpeg-build
        
    - name: Set executable permissions
      run: |
        ls -la android.sh  # Verifica permisos actuales
        chmod +x android.sh
        ls -la android.sh  # Verifica que ahora tenga +x
        
    # Build
    - name: Build FFmpeg with LAME
      run: |
        set -x
        echo "Parametro arch: ${{ matrix.arch }}"
        ./android.sh "${{ matrix.arch }}"
        
        # Verificación extrema
        echo "=== Estado del directorio después del script ==="
        find . -type d | grep -E "ffmpeg-build|lame-build"

    - name: Verify FFmpeg binary and LAME
      run: |
        echo "=== LAME libraries ==="
        ls -la "lame-build/$ANDROID_API_LEVEL/${{ matrix.arch }}/lib"
        file "lame-build/$ANDROID_API_LEVEL/${{ matrix.arch }}/lib/"*.so

        echo "=== FFmpeg binary ==="
        file "ffmpeg-build/$ANDROID_API_LEVEL/${{ matrix.arch }}/bin/ffmpeg"
        "ffmpeg-build/$ANDROID_API_LEVEL/${{ matrix.arch }}/bin/ffmpeg" -version

    # Upload artifacts
    - name: Upload FFmpeg artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-${{ matrix.arch }}
        path: |
          ffmpeg-build/$ANDROID_API_LEVEL/${{ matrix.arch }}
          lame-build/$ANDROID_API_LEVEL/${{ matrix.arch }}
        compression-level: 9
