name: Build FFmpeg with LAME support

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  LAME_VERSION: "3.100"
  ANDROID_API_LEVEL: 25
  NDK_VERSION: r27c

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86_64, x86]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # NDK setup
    - name: Set up Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: ${{ env.NDK_VERSION }}
        add-to-path: true
        
    - name: Verify NDK
      run: |
        echo "NDK Path: $ANDROID_NDK_HOME"
        ls -la $ANDROID_NDK_HOME/toolchains

    # Dependencies
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          nasm \
          git \
          wget

    # Download LAME
    - name: Download and extract LAME
      run: |
        wget https://downloads.sourceforge.net/project/lame/lame/${{ env.LAME_VERSION }}/lame-${{ env.LAME_VERSION }}.tar.gz -O lame.tar.gz
        tar -xzf lame.tar.gz
        mv lame-$LAME_VERSION lame
        rm lame.tar.gz
        echo "LAME_SOURCE_DIR=$GITHUB_WORKSPACE/lame" >> $GITHUB_ENV

    - name: Create build lame directory
      run: |
        mkdir -p lame-build
        echo "LAME_BUILD_DIR=$GITHUB_WORKSPACE/lame-build" >> $GITHUB_ENV
        
    - name: Set executable permissions
      run: |
        chmod +x android.sh
        
    # Build
    - name: Build LAME
      run: |
        set -x
        echo "Parametro arch: ${{ matrix.arch }}"
        ./android.sh "${{ matrix.arch }}"

    - name: Verify LAME
      run: |
        echo "=== LAME libraries ==="
        ls -la "lame-build/$ANDROID_API_LEVEL/${{ matrix.arch }}/lib"
        file "lame-build/$ANDROID_API_LEVEL/${{ matrix.arch }}/lib/"*.so

    # Upload artifacts
    - name: Upload FFmpeg artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lame-${{ matrix.arch }}
        path: |
          lame-build/$ANDROID_API_LEVEL/${{ matrix.arch }}
        compression-level: 9
