name: Build FFmpeg with LAME support

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  LAME_VERSION: "3.100"
  ANDROID_API_LEVEL: 25
  NDK_VERSION: r27c

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86_64, x86]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # NDK setup
    - name: Set up Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: ${{ env.NDK_VERSION }}
        add-to-path: true
        
    - name: Verify NDK
      run: |
        echo "NDK Path: $ANDROID_NDK_HOME"
        ls -la $ANDROID_NDK_HOME/toolchains

    # Dependencies
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          nasm \
          git \
          wget

    # Clone FFmpeg
    - name: Clone FFmpeg
      run: |
        git clone --depth 1 https://github.com/FFmpeg/FFmpeg.git ffmpeg
        echo "FFMPEG_SOURCE_DIR=$GITHUB_WORKSPACE/ffmpeg" >> $GITHUB_ENV

    - name: Create build lame directory
      run: |
        mkdir -p ffmpeg-build
        echo "FFMPEG_BUILD_DIR=$GITHUB_WORKSPACE/ffmpeg-build" >> $GITHUB_ENV
        
    - name: Set executable permissions
      run: |
        chmod +x android.sh
        
    # Build
    - name: Build FFmpeg
      run: |
        set -x
        echo "Parametro arch: ${{ matrix.arch }}"
        ./android.sh "${{ matrix.arch }}"

    - name: Verify FFmpeg
      run: |
        echo "=== FFmpeg binary ==="
        file "ffmpeg-build/$ANDROID_API_LEVEL/${{ matrix.arch }}/bin/ffmpeg"
        "ffmpeg-build/$ANDROID_API_LEVEL/${{ matrix.arch }}/bin/ffmpeg" -version

    # Upload artifacts
    - name: Upload FFmpeg artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-${{ matrix.arch }}
        path: |
          ffmpeg-build/${{ env.ANDROID_API_LEVEL }}/${{ matrix.arch }}
        compression-level: 9
